apiVersion: v1
kind: Service
metadata:
  name: node-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: node-service
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
