apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: node-service
    {{- include "node-service.labels" . | nindent 4 }}

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "node-service.selectorLabels" . | nindent 4 }}
    app: node-service
