apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: metrics
  name: metrics-sa-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metrics-sa-rolebinding
  namespace: metrics
subjects:
  - kind: ServiceAccount
    name: metrics-sa
    namespace: metrics
roleRef:
  kind: Role
  name: metrics-sa-role
  apiGroup: rbac.authorization.k8s.io
