apiVersion: v2
name: distributed-metrics
version: 0.1.0
dependencies:
  - name: node-service
    version: 0.1.0
    condition: node-service.enabled
  - name: gateway-service
    version: 0.1.0
    condition: gateway-service.enabled
  - name: kube-prometheus-stack
    version: "56.6.2"  # Укажи актуальную версию
    repository: https://prometheus-community.github.io/helm-charts