replicaCount: 2

image:
  repository: postgres
  tag: "15"
  pullPolicy: IfNotPresent

postgres:
  user: user
  password: pass

service:
  name: postgres-node
  port: 5432
  headless: true

persistence:
  storage: 1Gi
  storageClass: ""

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 5
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
